#!/bin/sh

mkdir -p opk/cores

cd /opt/sdlretro
git pull
mkdir -p build/
cd build/
cmake -DCMAKE_BUILD_TYPE=Release -DMODEL=funkey ..
make clean
make
/opt/FunKey-sdk/bin/arm-funkey-linux-musleabihf-strip src/sdlretro
cp src/sdlretro ../../libretro-tyrquake/opk

cd /opt/libretro-tyrquake
git fetch --all
git merge upstream/master
make clean
make
/opt/FunKey-sdk/bin/arm-funkey-linux-musleabihf-strip tyrquake_libretro.so
cp tyrquake_libretro.so opk/cores/

cp icons/tyrquake.png opk/
cp LICENSE.txt readme.txt readme-id.txt opk/

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GMenu2X entry file plus other things

print '[Desktop Entry]
Name=Quake
Comment=TyrQuake v0.62 for Libretro
Exec=sdlretro %f
Icon=tyrquake
Categories=games
SelectorFilter=pak' > opk/tyrquake.funkey-s.desktop

mksquashfs opk/ tyrquake_v0.62_funkey-s.opk -all-root -noappend -no-exports -no-xattrs

rm -rf opk/
