#!/bin/sh

mkdir -p opk/
git fetch --all
git merge upstream/master
make clean
make
/opt/FunKey-sdk/bin/arm-funkey-linux-musleabihf-strip tyrquake_libretro.so
cp tyrquake_libretro.so icons/tyrquake.png LICENSE.txt readme.txt readme-id.txt opk/

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GMenu2X entry file plus other things

print '[Desktop Entry]
Name=Quake
Comment=TyrQuake v0.62 for Libretro
Exec=picoarch ./tyrquake_libretro.so
Icon=tyrquake
Categories=games' > opk/tyrquake.funkey-s.desktop

rm -f *.opk
mksquashfs opk/ tyrquake_v0.62_funkey-s.opk -all-root -noappend -no-exports -no-xattrs

rm -rf opk/
